name: adventofcode

library:
  source-dirs: src

executables:
  adventofcode-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode

dependencies:
- base
- time
- text
- containers

ghc-options:
- -threaded

language: GHC2021
