name: adventofcode

library:
  source-dirs: src
  dependencies:
    - text
    - attoparsec
    - unordered-containers
    - safe
    - data-memocombinators
    - hashable
    - vector
    # https://williamyaoh.com/posts/2019-04-11-cheatsheet-to-regexes-in-haskell.html
    # - regex-tdfa
    # - regex-tdfa-text

executables:
  adventofcode-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qn1"'
    dependencies:
    - adventofcode
    - optparse-applicative
    - time

dependencies:
- base
- rio

ghc-options:
- -Wall
- -O2

language: GHC2021

default-extensions:
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DuplicateRecordFields
- FunctionalDependencies
- GADTs
- LambdaCase
- LexicalNegation
- LiberalTypeSynonyms
- MultiWayIf
- NoImplicitPrelude
- NumDecimals
- OverloadedRecordDot
- OverloadedStrings
- PatternSynonyms
- QuasiQuotes
- RecordWildCards
- TemplateHaskell
- TypeFamilies
- ViewPatterns
