name: adventofcode

library:
  source-dirs: src
  dependencies:
    - text
    - attoparsec
    - unordered-containers
    - safe
    - uglymemo
    - hashable
    - vector
    - pqueue
    - containers
    - vector-hashtables
    - vector-th-unbox
    - sbv
    - fgl
    - parallel

executables:
  adventofcode-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qn1"'
    dependencies:
    - adventofcode
    - optparse-applicative
    - time

dependencies:
- base
- rio

ghc-options:
- -Wall
- -O2

language: GHC2021

default-extensions:
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DuplicateRecordFields
- FunctionalDependencies
- GADTs
- LambdaCase
- LexicalNegation
- LiberalTypeSynonyms
- MultiWayIf
- NoImplicitPrelude
- NumDecimals
- OverloadedRecordDot
- OverloadedStrings
- PatternSynonyms
- QuasiQuotes
- RecordWildCards
- TemplateHaskell
- TypeFamilies
- ViewPatterns
